#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Si en 4 minutos no inicia el sistema correctamente se apaga por watchdog
/opt/mnggateway /dev/ttyAMA0 8 240
