#!/bin/sh

PREREQ=""
prereqs() { echo "$PREREQ"; }

case "$1" in
	prereqs)
		prereqs
		exit 0
	;;
esac

. "${CONFDIR}/initramfs.conf"
. /usr/share/initramfs-tools/hook-functions

# Install dropbear if explicitly enabled, or in case of a cryptroot setup if not explicitly disabled
if [ "${DROPBEAR}" = "y" ] || ( [ "${DROPBEAR}" != "n" ] && [ -r "/etc/crypttab" ] ); then
	if [ ! -x "/usr/sbin/dropbear" ]; then
		if [ "${DROPBEAR}" = "y" ]; then
			echo "dropbear: FAILURE: Dropbear not found!"
		else
			echo "dropbear: WARNING: Dropbear not found, remote unlocking of cryptroot via ssh won't work!"
		fi
	else
		rm -f "${DESTDIR}/sbin/dropbear"
		copy_exec "/usr/sbin/dropbear" "/sbin/"
		LIBC_DIR=$(ldd /usr/sbin/dropbear | sed -n -e 's,.* => \(/lib.*\)/libc\.so\..*,\1,p')
		for so in $(find "${LIBC_DIR}" -name 'libnss_compat*'); do
			copy_exec "${so}"
		done
		for keytype in "dss" "rsa"; do
			if [ ! -f "${CONFDIR}/etc/dropbear/dropbear_${keytype}_host_key" ]; then
				mkdir -p "${CONFDIR}/etc/dropbear"
				dropbearkey -t "${keytype}" -f "${CONFDIR}/etc/dropbear/dropbear_${keytype}_host_key"
			else
				if ! cmp -s "/etc/dropbear/dropbear_${keytype}_host_key" "${CONFDIR}/etc/dropbear/dropbear_${keytype}_host_key"; then
					echo "dropbear cryptroot setup: WARNING: /etc/dropbear/dropbear_${keytype}_host_key differs from ${CONFDIR}/etc/dropbear/dropbear_${keytype}_host_key: ssh clients may complain of changed host key"
				fi
			fi
		done
		cp -R ${CONFDIR}/etc/dropbear "${DESTDIR}/etc/"
		if [ ! -f "${CONFDIR}/root/.ssh/authorized_keys" ]; then
			mkdir -p "${CONFDIR}/root/.ssh"
			if [ ! -f "${CONFDIR}/root/.ssh/id_rsa.pub" ]; then
				dropbearkey -t rsa -f ${CONFDIR}/root/.ssh/id_rsa.dropbear
				/usr/lib/dropbear/dropbearconvert dropbear openssh ${CONFDIR}/root/.ssh/id_rsa.dropbear ${CONFDIR}/root/.ssh/id_rsa
				dropbearkey -y -f ${CONFDIR}/root/.ssh/id_rsa.dropbear | grep "^ssh-rsa " > ${CONFDIR}/root/.ssh/id_rsa.pub
			fi
			cat ${CONFDIR}/root/.ssh/id_rsa.pub >> ${CONFDIR}/root/.ssh/authorized_keys
		fi
		mkdir -p "${DESTDIR}/root/.ssh"
		cp -R ${CONFDIR}/root "${DESTDIR}/."
		echo 'passwd: compat' > "${DESTDIR}/etc/nsswitch.conf"
		echo "root:x:0:0:root:/root:/bin/sh" > "${DESTDIR}/etc/passwd"
    echo 'root:*:17438:0:99999:7:::' > ${DESTDIR}/etc/shadow
    cat ${CONFDIR}/etc/profile > ${DESTDIR}/etc/profile
    chmod 600 ${DESTDIR}/etc/shadow
	fi
fi

