#!/bin/sh

PREREQ=""
prereqs() { echo "$PREREQ"; }

case "$1" in
	prereqs)
		prereqs
		exit 0
	;;
esac

. "${CONFDIR}/initramfs.conf"
. /usr/share/initramfs-tools/hook-functions

force_load vfat
force_load ext4

copy_exec /sbin/fdisk
copy_exec /sbin/mkfs
