#!/bin/sh

PREREQ=""
prereqs() { echo "$PREREQ"; }

case "$1" in
	prereqs)
		prereqs
		exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

if [ ! -x /opt/mnggateway ]; then
  printf "Hook mnggateway requiere comando /opt/mnggateway"
  exit 1
fi

copy_exec "/opt/mnggateway"
