#!/bin/sh

PREREQ=""
prereqs() { echo "$PREREQ"; }

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

if [ ! -x /usr/sbin/ntpdate ]; then
  printf "Hook ntp requiere el comando ntpdate"
  exit 1
fi

copy_exec "/usr/sbin/ntpdate"

cat >"${DESTDIR}/etc/services" <<EOF
ssh       22/tcp                  # SSH Remote Login Protocol
http      80/tcp    www           # WorldWideWeb HTTP
nntp      119/tcp   readnews untp # USENET News Transfer Protocol
ntp       123/tcp
ntp       123/udp                 # Network Time Protocol
https     443/tcp                 # http protocol over TLS/SSL
nntps     563/tcp   snntp         # NNTP over SSL
openvpn   1194/tcp
openvpn   1194/udp
http-alt  8080/tcp  webcache      # WWW caching service
http-alt  8080/udp
EOF
